In [6]:
import numpy as np


In [7]:
list = [1,2,3,4,5]

In [8]:
list2 = ["sam",1,True]

In [13]:
np1 = np.array([0,3,2,1,4,5,7,6,8,9])
print(np1)

[0 3 2 1 4 5 7 6 8 9]


In [10]:
print(np1.shape)

(10,)


In [14]:
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
np3 = np.arange(0,10,3)
print(np3)

[0 3 6 9]


In [18]:
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
np5 = np.zeros((3,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
np6 = np.full((10),6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [22]:
# Multidimensional full
np7 = np.full((2,5),1)
print(np7)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
# convert python list to np
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)

[1 2 3 4 5]
