In [1]:
import numpy as np

In [2]:
#numpy universal function?

In [6]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9,-10])
print(np1)

[  0   1   2   3   4   5   6   7   8   9 -10]


In [7]:
# square route of each element
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.                nan]


C:\Users\Acer\AppData\Local\Temp\ipykernel_16864\3712433972.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [8]:
print(np.absolute(np1))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
print(np.sign(np1)))

SyntaxError: unmatched ')' (2716923446.py, line 1)

In [10]:
print(np.sign(np1))

[ 0  1  1  1  1  1  1  1  1  1 -1]


In [11]:
np2 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.sign(np2))

[0 1 1 1 1 1 1 1 1 1]


In [12]:
print(np.log(np2))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Acer\AppData\Local\Temp\ipykernel_16864\2926583669.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(np2))
