In [1]:
import numpy as np

In [30]:
np1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np1:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
# use np.nditer() for each element in one line
for x in np.nditer(np1):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
# for sorting numpy array np.sort()
np2 = np.array([0,7,6,3,1,2,4,8,9,5])
print(np.sort(np2))

[0 1 2 3 4 5 6 7 8 9]


In [36]:
x = np.where(np2 == 5)
print(np2)
print(x)

[0 7 6 3 1 2 4 8 9 5]
(array([9]),)


In [38]:
# print even numbers
y = np.where(np2 % 2 == 0)
print(np2)
print(y[0])

[0 7 6 3 1 2 4 8 9 5]
[0 2 5 6 7]
